services:
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      MSSQL_SA_PASSWORD: "OmarUtvecklar1991"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    hostname: "db"

  socialhub:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db



    
